project:
  type: website
  output-dir: docs

website:
  title: "Jiajing's Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Hobbies
        href: hobbies.qmd

format:
  html:
    theme: vapor
    css: styles.css
    toc: true



